sudo: false
language: php
php:
  - nightly
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: nightly

install:
  - composer global require squizlabs/php_codesniffer

script:
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
